$schema: ../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  type: console
  level: debug
  batch_size: 100
  flush_interval: 2
  max_queue_size: 2048
  http_endpoint:
  http_headers:
  http_timeout: 5

mcp:
  servers:
    gmail:
    filesystem:
      command: "uv run"
      args:
        [
          "--directory",
          "/Users/jasonsummer/Documents/personal_dev/model_context_protocol/gmail",
          "run",
          "gmail",
          "--creds-file-path",
          "/Users/jasonsummer/.google/api_creds.json",
          "--token-path",
          "/Users/jasonsummer/.google/token_creds.json"
        ]

openai:
  # Secrets (API keys, etc.) are stored in an mcp_agent.secrets.yaml file which can be gitignored
  default_model: gpt-4o
anthropic:
  default_model: claude-3.5-sonnet
